# Use the official Python image as a base
FROM python:3.12-slim

# Set the working directory
RUN python -m venv --copies /opt/venv

# Copy the requirements file and install dependencies
RUN /opt/venv/bin/python -m pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on (e.g., 5000)
EXPOSE 5000

# Specify the command to run the application using a production-ready server
# Gunicorn is a popular choice for Flask
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "server:app"]